In [2]:
import numpy as np
import pandas as pd
from sklearn.linear_model import Perceptron

train_x = pd.read_csv('csv_files/train_binary_x.csv')
train_y = pd.read_csv('csv_files/train_binary_y.csv')
test_x = pd.read_csv('csv_files/test_binary_x.csv')
test_y = pd.read_csv('csv_files/test_binary_y.csv')

train_x_IVF = pd.read_csv('csv_files/x_train_binary_IVF.csv')
train_y_IVF = pd.read_csv('csv_files/y_train_binary_IVF.csv')
test_x_IVF = pd.read_csv('csv_files/x_test_binary_IVF.csv')
test_y_IVF = pd.read_csv('csv_files/y_test_binary_IVF.csv')

In [3]:
print('Test_x shape: ', test_x.shape)
print('Train_x shape: ', train_x.shape)
print('Train_y shape: ', train_y.shape)

print('Test_x_IVF shape: ', test_x_IVF.shape)
print('Train_x_IVF shape: ', train_x_IVF.shape)
print('Train_y_IVF shape: ', train_y_IVF.shape)

Test_x shape:  (31226, 28)
Train_x shape:  (124904, 28)
Train_y shape:  (124904, 1)
Test_x_IVF shape:  (31226, 27)
Train_x_IVF shape:  (124904, 27)
Train_y_IVF shape:  (124904, 1)


In [4]:
X = train_x.values
y = train_y.astype(int).values.ravel()

per_clf = Perceptron(
    max_iter=1000, 
    tol=1e-3, 
    random_state=42)

per_clf.fit(X, y)

y_pred = per_clf.predict(test_x.values)

In [5]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [6]:
from sklearn.metrics import classification_report

print(classification_report(test_y, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98     27451
           1       0.77      1.00      0.87      3775

    accuracy                           0.96     31226
   macro avg       0.89      0.98      0.92     31226
weighted avg       0.97      0.96      0.97     31226



In [22]:
print('Confusion Matrix1:')
print(confusion_matrix(test_y, y_pred))

Confusion Matrix1:
[[26326  1125]
 [    0  3775]]


In [7]:
X_IVF = train_x_IVF.values
y_IVF = train_y_IVF.astype(int).values.ravel()

per_clf = Perceptron(
    max_iter=1000, 
    tol=1e-3, 
    random_state=42)

per_clf.fit(X_IVF, y_IVF)

y_pred_IVF = per_clf.predict(test_x_IVF.values)

In [8]:
y_pred_IVF

array([0, 0, 0, ..., 0, 0, 0])

In [37]:
for col in X_IVF.np.ndarray:
    print(col)

AttributeError: 'numpy.ndarray' object has no attribute 'np'

In [9]:
from sklearn.metrics import classification_report

print(classification_report(test_y_IVF, y_pred_IVF))

              precision    recall  f1-score   support

           0       0.84      1.00      0.91     26270
           1       0.60      0.01      0.02      4956

    accuracy                           0.84     31226
   macro avg       0.72      0.51      0.47     31226
weighted avg       0.80      0.84      0.77     31226



In [15]:
# Using SMOTE to resample target data 
from imblearn.over_sampling import SMOTE

smt = SMOTE(random_state = 100, sampling_strategy = 1.0)
train_x_smt, train_y_smt = smt.fit_resample(train_x, train_y)

smt_IVF = SMOTE(random_state = 100, sampling_strategy = 1.0)
train_x_smt_IVF, train_y_smt_IVF = smt_IVF.fit_resample(train_x_IVF, train_y_IVF)

In [16]:
# SMOTE values on y train pregnancy model & y train IVF successful model 
print('SMOTE for live birth')
print(train_y_smt.value_counts())
print('\n')
print('SMOTE for pregnant')
print(train_y_smt_IVF.value_counts())

SMOTE for live birth
LiveBirth
0            109803
1            109803
dtype: int64


SMOTE for pregnant
Pregnant
0           105080
1           105080
dtype: int64


In [26]:
from sklearn.metrics import confusion_matrix

# Perceptron model w/SMOTE for pregnancy 
X1 = train_x_smt.values
y1 = train_y_smt.astype(int).values.ravel()
per_clf1 = Perceptron(max_iter=1000, tol=1e-3, random_state=42)
per_clf1.fit(X1, y1)
y_pred = per_clf1.predict(test_x.values)
print('Confusion Matrix1:')
print(confusion_matrix(test_y, y_pred))
print('Classification Report1:')
print(classification_report(test_y, y_pred))
print('\n')

# Perceptron model w/SMOTE for live birth from IVF
X2 = train_x_smt_IVF.values
y2 = train_y_smt_IVF.astype(int).values.ravel()
per_clf2 = Perceptron(max_iter=1000, tol=1e-3, random_state=42)
per_clf2.fit(X2, y2)
y_pred_IVF = per_clf2.predict(test_x_IVF.values)
print('Confusion Matrix1:')
print(confusion_matrix(test_y_IVF, y_pred_IVF))
print('Classification Report1:')
print(classification_report(test_y_IVF, y_pred_IVF))
print('\n')

Confusion Matrix1:
[[26321  1130]
 [    0  3775]]
Classification Report1:
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     27451
           1       0.77      1.00      0.87      3775

    accuracy                           0.96     31226
   macro avg       0.88      0.98      0.92     31226
weighted avg       0.97      0.96      0.97     31226



Confusion Matrix1:
[[25225  1045]
 [ 3747  1209]]
Classification Report1:
              precision    recall  f1-score   support

           0       0.87      0.96      0.91     26270
           1       0.54      0.24      0.34      4956

    accuracy                           0.85     31226
   macro avg       0.70      0.60      0.62     31226
weighted avg       0.82      0.85      0.82     31226





In [32]:
# Neural networks (including perceptron) do not have feature importance so I am looking at permutation importance
inp = input(train_x_IVF)
x = Dense(128, activation='relu')(inp)
x = Dense(32, activation='relu')(x)
out = Dense(1)(x)
model = Model(inp, out)
model.compile(optimizer='adam', loss='mse')
model.fit(scaled_train, (train_y_IVF - train_y_IVF.mean())/train_y_IVF.std(),epochs=100,batch_size=128,verbose=2)

KeyboardInterrupt: Interrupted by user

In [34]:
import matplotlib.pyplot as plt
plt.bar(range(train_x_IVF.shape[1]), (final_score - MAE)/MAE*100)
plt.xticks(range(train_x_IVF.shape[1]), ['AT','V','AP','RH'])

NameError: name 'final_score' is not defined